name: Build Go
run-name: Building executables
on:
  workflow_dispatch:
  push:
    tags:
      - '**'
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'README'
      - 'LICENSE'
      - 'images/*'
      - 'Makefile'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'README'
      - 'LICENSE'
      - 'images/*'
      - 'Makefile'
      - '.gitignore'

permissions:
  contents: write
  packages: write

env:
  IS_TAG: ${{ github.ref_type == 'tag' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run tests
        run: |
          make tests_ci

      - name: Building deb
        run: |
          make build_deb

      - name: Building exe
        run: |
          make build_win

      - name: Publish Release
        uses: ncipollo/release-action@v1
        if: env.IS_TAG == 'true'
        with:
            artifacts: "artifacts/fn-config-helper*"
            tag: ${{ github.ref_name }}
            skipIfReleaseExists: true
            makeLatest: true
            # bodyFile: ReleaseNotes.md

